version = 0.1
[default.deploy.parameters]
stack_name = "slack-app"
s3_bucket = "slack-app-deployment"
s3_prefix = "slack-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
image_repositories = []
